### ISSUE TITLE
Ministério da Segurança Pública Digital

### ISSUE THREAD

**Issue by AndreHS2020** [dadosgovbr/processo-participacao-social-inda#8]
* Leis e regras 

* Violações e restrições

**Comment by augusto-herrmann** [comment]
Olá. Parece que você é novo no Github. Leia para aprender para que servem *issues*:

* [Pra que serve o issue no Github?](https://pt.stackoverflow.com/questions/101706/pra-que-serve-o-issue-no-github)
* [About issues](https://help.github.com/en/github/managing-your-work-on-github/about-issues)
